---
- name : Create Cluster
  hosts: localhost

  tasks:
  - name: Create Cluster
    local_action:
      module: vmware_cluster
      hostname: 192.168.72.144
      username: administrator@vsphere.local
      password: 'vmware'
      datacenter_name: 'noyon.carl'
      cluster_name: carl.noyon
      enable_ha: yes
      enable_drs: yes
      enable_vsan: no
      validate_certs: no
#    delegate_to: localhost
#    register: vmfacts
