---
- name: Create a VM from a template
  hosts: localhost
  vars:
    notes: 'Created by Ansible'
    vcenter_hostname: 192.168.72.144
    vcenter_user: administrator@vsphere.local
    vcenter_pass: vmware
    datastore: datastore1
    network: VM Network
    memory: 10
    cpucount: 1
    osid: debin7_64Guest

  tasks:
  - name: Create a VM from template
    vmware_guest:
      hostname: 192.168.72.144
      username: administrator@vsphere.local
      password: 'vmware'
      validate_certs: no
      esxi_hostname: 192.168.72.155
      datacenter: noyon.carl
      folder: /test/
      name: vm1.vm
      state: present
      template: test
      disk:
      - size_gb: 1
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: 512
        num_cpus: 1
        scsi: paravirtual
#      networks:
#      - name: 'VM Network'
#        mac: aa:bb:dd:aa:00:14
      wait_for_ip_address: yes
#    delegate_to: localhost
    register: deploy
