---
- name : Create Datacenter
  hosts: localhost

  tasks:
  - name: Create Datacenter
    local_action:
      module: vmware_datacenter
      hostname: 192.168.72.144
      username: administrator@vsphere.local
      password: 'vmware'
      datacenter_name: 'noyon.carl'
      state: present
      validate_certs: no
#    delegate_to: localhost
#    register: vmfacts
